# Generated by Django 3.1.4 on 2020-12-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201210_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='user',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
