# Generated by Django 3.1.4 on 2020-12-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_results_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='results',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='results',
            name='user',
        ),
    ]
