# Generated by Django 3.1.4 on 2020-12-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_results_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='mat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='t3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='t4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='tat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='tsh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImportedResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('results', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.results')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registereduser')),
            ],
        ),
    ]
