# Generated by Django 3.1.4 on 2020-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='mat',
        ),
        migrations.RemoveField(
            model_name='results',
            name='t3',
        ),
        migrations.RemoveField(
            model_name='results',
            name='t4',
        ),
        migrations.RemoveField(
            model_name='results',
            name='tat',
        ),
        migrations.RemoveField(
            model_name='results',
            name='tsh',
        ),
        migrations.RemoveField(
            model_name='results',
            name='user',
        ),
        migrations.AddField(
            model_name='results',
            name='results_type',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
