# Generated by Django 3.1.4 on 2020-12-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_importedresults_result_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='results_type',
        ),
        migrations.AddField(
            model_name='results',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='ft3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='ft4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='mat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='tat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='tsh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registereduser'),
        ),
        migrations.DeleteModel(
            name='ImportedResults',
        ),
    ]
