# Generated by Django 3.1.4 on 2020-12-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201212_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
